version: '3'

services:
  mongodb:
    image: "mongo:latest"
    environment:
      MONGO_INITDB_DATABASE: "newsBotDatabase"
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "admin123"
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "admin"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "admin123"
      ME_CONFIG_MONGODB_URL: "mongodb://admin:admin123@mongodb:27017/?authSource=admin"