spring:
  application:
    name: "crypto-news-bot"
  data:
    mongodb:
      uri: mongodb://admin:admin123@mongodb:27017/?authSource=admin
      username: admin
      password: admin123
      auto-index-creation: true
  ai:
    openai:
      api-key: ""
#      base-url: "https://api.openai.com"
news-data:
  client:
    api-key: ""
news-api:
    client:
      api-key: ""

tg:
  bot:
    api-key: "key"
    group-id:
